name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List files in the working directory where GHA sees
      run: ls -la /home/runner/work/PLAYWRIGHT_CUCUMBER_TS

    - name: List files in the working directory
      run: ls -R

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm run test:withreport

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: test-results/**  # Ensure this path matches where your reports are generated
        retention-days: 30
